// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBTattJ3Qr5rHRyb9AZ6rMPwLRU0jXxs',
    appId: '1:35361249911:web:e6b4d00933ea07952d0472',
    messagingSenderId: '35361249911',
    projectId: 'testing-cli-3f219',
    authDomain: 'testing-cli-3f219.firebaseapp.com',
    storageBucket: 'testing-cli-3f219.firebasestorage.app',
    measurementId: 'G-XPYGVG5CN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArrT03d2ReFTXg7l5NKb1WourSNpHYf7I',
    appId: '1:35361249911:android:4d61e4f4d8bbc0672d0472',
    messagingSenderId: '35361249911',
    projectId: 'testing-cli-3f219',
    storageBucket: 'testing-cli-3f219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6kT0O9v9cN2Oe8dg50Ixyo_mGyj3Qdg',
    appId: '1:35361249911:ios:5da82261ed567e232d0472',
    messagingSenderId: '35361249911',
    projectId: 'testing-cli-3f219',
    storageBucket: 'testing-cli-3f219.firebasestorage.app',
    iosBundleId: 'com.example.tourpulse',
  );
}
